site_name: Python Basics
site_description: Python Basics
site_url: https://zhangfan9607243.github.io/NavigationBA-PythonBasics/
repo_url: https://github.com/zhangfan9607243/NavigationBA-PythonBasics
edit_uri: edit/main/docs/

theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - content.code.copy
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: light blue
    - scheme: slate
      primary: indigo
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: 切换到日间模式

nav:
  - 首页: index.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences