site_name: Python Basics
site_description: Python Basics
site_url: https://zhangfan9607243.github.io/NavigationBA-PythonBasics/
repo_url: https://github.com/zhangfan9607243/NavigationBA-PythonBasics
edit_uri: edit/main/docs/

theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - content.code.copy
    - toc.integrate

nav:
  - 首页: index.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
