site_name: 领航国际教育 - Business Analytics专业自学系列课程
site_description: 领航国际教育 - Business Analytics专业自学系列课程
site_url: https://zhangfan9607243.github.io/NavigationBA-PythonBasics/
repo_url: https://github.com/zhangfan9607243/NavigationBA-PythonBasics
edit_uri: edit/main/docs/

theme:
  name: material
  language: zh
  features:
    - navigation.tabs        # 顶部导航标签
    - navigation.sections    # 子导航分组
    - navigation.top
    - navigation.tracking
    - content.code.copy
    - toc.follow
  palette:
    - scheme: default
      primary: blue   # 主色（导航栏背景）
      accent: blue    # 强调色（按钮、链接高亮）
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: 切换到日间模式

nav:
  - 首页: index.md
  - Module 1 - Python基础: 
    - Topic 1: Module1_PythonBasics/Topic1.md
    - Topic 2: Module1_PythonBasics/Topic2.md
    - Topic 3: Module1_PythonBasics/Topic3.md
    - Topic 4: Module1_PythonBasics/Topic4.md
  - Module 2 - Python面向对象:
    - Topic 1: Module2_PythonOOP/Topic1.md
    - Topic 2: Module2_PythonOOP/Topic2.md
    - Topic 3: Module2_PythonOOP/Topic3.md
    - Topic 4: Module2_PythonOOP/Topic4.md
  - Module 3 - Python数据分析:
    - Topic 1: Module3_PythonDataAnalysis/Topic1.md
    - Topic 2: Module3_PythonDataAnalysis/Topic2.md
    - Topic 3: Module3_PythonDataAnalysis/Topic3.md
    - Topic 4: Module3_PythonDataAnalysis/Topic4.md
  - Module 4 - R基础:
    - Topic 1: Module4_RBasics/Topic1.md
    - Topic 2: Module4_RBasics/Topic2.md
    - Topic 3: Module4_RBasics/Topic3.md
    - Topic 4: Module4_RBasics/Topic4.md
  - Module 5 - SQL基础:
    - Topic 1: Module5_SQLBasics/Topic1.md
    - Topic 2: Module5_SQLBasics/Topic2.md
    - Topic 3: Module5_SQLBasics/Topic3.md
    - Topic 4: Module5_SQLBasics/Topic4.md
  - Module 6 - Tableau基础: 
    - Topic 1: Module6_Tableau/Topic1.md
    - Topic 2: Module6_Tableau/Topic2.md
    - Topic 3: Module6_Tableau/Topic3.md
    - Topic 4: Module6_Tableau/Topic4.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
      title: Table of Contents
  - pymdownx.highlight
  - pymdownx.superfences